name: PulseRankedBW
version: '${project.version}'
main: br.com.pulse.ranked.Main
depend: [PRanked4sBOT]
softdepend: [BedWars2023, PlaceholderAPI]
commands:
  joinqueue:
    description: Entrar em uma fila
    aliases: [joinfila, entrarfila]
  leavequeue:
    description: Sair de uma fila
    aliases: [leavefila, sairfila]
  elo:
    description: Sobre elo
  rank:
    description: Ver rank
    aliases: [ranqueamento]
  mvp:
    description: Quantidade de vezes mvp
    aliases: [mostvaluableplayer]
  partida:
    description: Ver informações sobre uma partida
    aliases: [matchinfo, infopartida, partidainfo]
  rankdisplay:
    aliases: [displayrank, mostrarrank]
